### ISSUE TITLE
Join-Object w

### ISSUE THREAD

**Issue by Congenial-GmbH** [iRon7/Join-Object#35] opened 2023-03-06 11:12 UTC

**Comment by Congenial-GmbH** [comment] 2023-03-06 11:48
Hi, 

Under certain circumstances `Join-Object` unintentionally overwrites some columns in the result (cf. example code below).

**INPUT**

Table $A
```
ID_1 ID_2 Name JoinID
---- ---- ---- ------
   1 a    John 1, a
```

Table $B

```
ID_1 ID_2 Partner JoinID
---- ---- ------- ------
   1 a    Nancy   1, a
```

Note: `JoinID` has been created from `ID_1` and `ID_2` using
```pwsh
$row.JoinID = (@( $row.ID_1, $row.ID_2 ) | Join-String -Separator ', ' )
```


**ISSUE**

```pwsh
Join-Object -LeftObject $A -RightObject $B -JoinType 'Left' -On 'JoinID' -Equals 'JoinID'
```

This results in unwanted alteration of columns `ID_1` and `ID_2`:

```
ID_1   ID_2   Name JoinID Partner
----   ----   ---- ------ -------
{1, 1} {a, a} John 1, a   Nancy
```


**CODE EXAMPLE**

```pwsh
# Possible Bug in PowersShell Module 'JoinModule'
# ----------------------------------------------

# Dummy example 

# Step 0: Create Input Tables

$A = @(
    [PSCustomObject]@{
        ID_1 = 1
        ID_2 = 'a'
        Name = "John"
    }
)
$B = @(
    [PSCustomObject]@{
        ID_1 = 1
        ID_2 = 'a'
        Partner = "Nancy"
    }
)


# Step 1 : Append a key named 'JoinID'
#          compsed of 'ID_1' and 'ID_2'

$A = $A | Select-Object * , 'JoinID'
$B = $B | Select-Object * , 'JoinID'

foreach ($row in $A)
{
    $row.JoinID = (@( $row.ID_1, $row.ID_2 ) | Join-String -Separator ', ' )
}
foreach ($row in $B)
{
    $row.JoinID = (@( $row.ID_1, $row.ID_2 ) | Join-String -Separator ', ' )
}

$A | Out-String
$B | Out-String

$result = Join-Object -LeftObject $A -RightObject $B -JoinType 'Left' -On 'JoinID' -Equals 'JoinID'
$result | Format-Table | Out-String

# Issue:
# Fields 'ID_1' and 'ID_2' have been overwritten
```

**OUTPUT**

```
ID_1 ID_2 Name JoinID
---- ---- ---- ------
   1 a    John 1, a



ID_1 ID_2 Partner JoinID
---- ---- ------- ------
   1 a    Nancy   1, a



ID_1   ID_2   Name JoinID Partner
----   ----   ---- ------ -------
{1, 1} {a, a} John 1, a   Nancy
```

**Comment by iRon7** [comment] 2023-03-06 14:51
This is expected behavior.

Any property (column) that is not related, is joined as an array by default simply because (normally) there is no relation with the concerned values (`ID_1` and `ID_2`) and therefore they can't be assumed to be equal:

```PowerShell
$a = [PSCustomObject]@{ ID_1 = 1; ID_2 = 'a'; Name = "John"; JoinId = '1, a' }
$b = [PSCustomObject]@{ ID_1 = 2; ID_2 = 'b'; Partner = "Nancy"; JoinId = '1, a' }
$a |Join $b -On JoinId |Format-Table

ID_1   ID_2   Name JoinId Partner
----   ----   ---- ------ -------
{1, 2} {a, b} John 1, a   Nancy
```
To prevent the unrelated properties to join as an array, you might consider the `-Discern` (alias `-Name`) switch:
```PowerShell
$a |Join $b -On JoinId -Name a_,b_ |Format-Table

a_ID_1 b_ID_1 a_ID_2 b_ID_2 Name JoinId Partner
------ ------ ------ ------ ---- ------ -------
     1      2 a      b      John 1, a   Nancy
```

Anyways, I don't think there is any reason for you to create this particular "`JoinId`" property as you might simply join the objects based on multiple properties (aka columns). Any property that is related (where you apply the `-on` parameter to), 
might be presumed equal an therefore the (equal) values of either side will be joined to a single value:

```PowerShell
$a = [PSCustomObject]@{ ID_1 = 1; ID_2 = 'a'; Name = "John" }
$b = [PSCustomObject]@{ ID_1 = 1; ID_2 = 'a'; Partner = "Nancy" }
$a |Join $b -on ID_1,ID_2

ID_1 ID_2 Name Partner
---- ---- ---- -------
   1 a    John Nancy
```

At the other hand, if you really want to continue with the"`JoinId`" and have the `ID_1` and `ID_2` "merged" (overwritten), you might consider the `Update-Command` command instead (which "*updates the left object with the related right object*"):
```PowerShell
$a = [PSCustomObject]@{ ID_1 = 1; ID_2 = 'a'; Name = "John"; JoinId = '1, a' }
$b = [PSCustomObject]@{ ID_1 = 2; ID_2 = 'b'; Partner = "Nancy"; JoinId = '1, a' }
$a |Update $b -On JoinId |Format-Table

ID_1 ID_2 Name JoinId Partner
---- ---- ---- ------ -------
   2 b    John 1, a   Nancy
```
Note that with the later `Update-Object`, the left properties (`ID_1 = 1` and `ID_2 = 'a'`) is overwritten with the right properties (`ID_1 = 2` and `ID_2 = 'b'`).

**Closed as completed** 2023-03-13 07:18 UTC
Labels: question
